name: GitHub Actions Build and Deploy ZKPVOTE
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependency
        run: yarn install

      - name: Set base URL in Env
        if: ${{ github.repository_owner != 'vechain-community' }}
        run: |
          echo 'BASE<<EOF' >> $GITHUB_ENV
          echo "$GITHUB_REPOSITORY" | awk -F / '{print "/"$2"/"}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Buid Website
        run: |
          yarn run build
          cp dist/index.html dist/404.html

      - name: Deploy Without CNAME
        if: ${{ github.repository_owner != 'vechain-community' }}

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
          force_orphan: true

      - name: Deploy With CNAME
        if: ${{ github.repository_owner == 'vechain-community' }}

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
          cname: zkpvote.vechain.org
          force_orphan: true

